# configuration: production
spring:
   config:
      activate:
         on-profile: production

   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3307/webdb?charset=utf8
      username: webdb
      password: '{cipher}AQAgArKRSQf3KHKocgtTUJdx5jxW50XZ+J1SUU8Ed03bKGcSPYyjYJjNCmhahKTVaR4NOKCsOM60dmR8fdVPNK1bBd9oyKjl25OSJuWBUppmzo03zH2kcJEERPisk41r0gfDmk9t6GOg2n5uzJsPr/SJwbXgobPCMASV3bGdb0to+Sd5ZTmdSObIn1QPgEBD6k+Af2RaJPN/XJk6h4g/z3jA9npw0/LeIQchhIBaCfylY1F/ec7P/v2mUR/AVv/6aRSLynNJkemlas6pj0KwKV96BnP4JEXmX+zekmC0fzHJPlb/d3ykbUqqBli1Fk36ruAbZUj6Aup6gzGpJ1H+AIk/jgs34GxWg7b9nPlKRD4AFyUWaVqIEcl4gHjGPenFhfs='
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      com:
         poscodx:
            msa:
               service:
                  guestbook:
                     exception: ERROR
                              
eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://192.168.0.186:8761/eureka